---
- name: Install Vector
  hosts: all
  handlers:
    - name: Check succses install vector
      ansible.builtin.shell: "vector --version"
      register: out
      tags: vector
    - name: debug details
      debug:
        msg: "{{ out.stdout }}"
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/vector-{{ vector_version }}.tar.gz"
      tags: vector
    - name: Create directory for Vector
      file:
        state: directory
        path: "{{ vector_home }}"
      tags: vector
    - name: extractor presents
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present
      tags: vector
    - name: Extract vector in directory
      ansible.builtin.unarchive:
        src: "/vector-{{ vector_version }}.tar.gz"
        dest: "{{ vector_home }}"
        extra_opts: [ --strip-components=2 ]
        remote_src: yes
      tags: vector
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ vector_home }}/bin/vector"
        dest: "/usr/bin/vector"
        owner: root
        group: root
        state: link
      tags: vector
      notify:
        - Check succses install vector
        - debug details
